name: sabiwork
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # get: ^4.6.1
  get: 4.5.1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.22.0
  image_stack: ^2.1.0
  flutter_zoom_drawer: ^2.1.1
  http: ^0.13.3
  shared_preferences: ^2.0.5
  another_flushbar: ^1.10.24
  shimmer: ^2.0.0
  jiffy: ^4.0.0
  gender_picker: ^1.1.0
  # image_picker: ^0.7.4
  image_picker: ^0.8.4
  image_cropper: ^1.3.0
  dio: ^4.0.3
  http_parser: ^4.0.0
  intl: ^0.17.0
  cached_network_image: ^3.1.0+1
  lottie: ^1.2.1
  tutorial_coach_mark: ^1.1.1
  share_plus: ^2.1.4
  pinput: ^1.2.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  url_launcher: ^6.0.10
  flutter_phone_direct_caller: ^2.0.0
  firebase_core: ^1.9.0
  firebase_messaging: ^11.0.0
  flutter_local_notifications: ^9.1.4
  emoji_picker_flutter: ^1.1.1
  basic_utils: ^3.8.1
  font_awesome_flutter: ^9.2.0
  flutter_spinkit: ^5.1.0
  blurrycontainer: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/sabiwork.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/jost/Jost-LightItalic.otf
        - asset: assets/fonts/jost/Jost-Bold.otf
        - asset: assets/fonts/jost/Jost-BoldItalic.otf
        - asset: assets/fonts/jost/Jost-BoldItalic.otf
        - asset: assets/fonts/jost/Jost-Italic.otf
        - asset: assets/fonts/jost/Jost-Light.otf
        - asset: assets/fonts/jost/Jost-Medium.otf
        - asset: assets/fonts/jost/Jost-MediumItalic.otf
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
